#!/bin/bash
set -e

#chmod +x /usr/lib/itmon.reporter.py


cd /usr/lib/itmon
chmod 777 itmon.sh
python3 -m venv itmon-env
source itmon-env/bin/activate
pip install -r requirements.txt


# Enable and start the service
systemctl enable itmon.service

systemctl start itmon.service
exit 0